apiVersion: v2
name: nats
description: NATS con JetStream (broker de mensajeria asincrona) - Practica 6, Software Avanzado, USAC, carne 201901844
type: application
version: "0.1.0"
appVersion: "2.10"
