image:
  repository: nats
  tag: "2.10-alpine"
  pullPolicy: IfNotPresent
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits: { cpu: 300m, memory: 384Mi }
persistence:
  size: 1Gi
  storageClass: ""
jetstream:
  maxMemory: "256MB"
  maxFile: "1GB"
serviceAccount:
  create: true
auth:
  username: sa_admin
  # password: se define en values-secrets.yaml (no se versiona en el repo)
