apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace | default "sa-p5" }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 3000 }}
      targetPort: 3000
      {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
