api-gateway:
  image:
    tag: "p8-v1.0.0"
auth-service:
  image:
    tag: "p8-v1.0.0"
reserva-service:
  image:
    tag: "p8-v1.0.0"
notificacion-service:
  image:
    tag: "p8-v1.0.0"
cronjob-registro:
  image:
    tag: "p8-v1.0.0"
cronjob-resumen:
  image:
    tag: "p8-v1.0.0"
pago-service:
  image:
    tag: "p8-v1.0.0"
