apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" . }}
  namespace: {{ .Values.global.namespace | default "sa-p5" }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitor
      port: 8222
      targetPort: 8222
