{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nats.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace | default "sa-p5" }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
{{- end }}
